"""
build_v50_dynamic_ejecta_particle_pilot.py
=========================================

Generate V5A decks with explicit ejecta marker shell patches above the V4C
pre-deleted crater.

Run from project root:
    python scripts\\build_v50_dynamic_ejecta_particle_pilot.py
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from copy import deepcopy
from pathlib import Path

_THIS_DIR = Path(__file__).resolve().parent
if str(_THIS_DIR) not in sys.path:
    sys.path.insert(0, str(_THIS_DIR))

from _build_v17_case import build_mesh, f10, i10, write_k  # noqa: E402
from build_v41_dynamic_ablation_deletion import (  # noqa: E402
    V41Case,
    build_k_text,
    load_toml,
    vapor_radius_um,
)


if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass


def ejecta_marker_geometry(mesh, case: V41Case, cfg: dict, v17_cfg: dict,
                           start_node: int, start_elem: int) -> tuple[list[str], list[str], list[str], list[dict[str, str]], dict[str, int]]:
    layer = cfg["ejecta_layer"]
    delete = cfg["deletion_model"]
    laser = v17_cfg["laser"]
    threshold = float(delete["vapor_threshold_Ep_uJ"])
    r_vap_um = vapor_radius_um(case.Ep_uJ, threshold, float(laser["spot_radius_um"]))
    r_max_um = max(float(layer["radial_step_um"]), r_vap_um * float(layer["radial_extent_fraction"]))

    dr = float(layer["radial_step_um"])
    dz = float(layer["vertical_spacing_um"])
    half = 0.5 * float(layer["patch_size_um"]) * 1.0e-3
    top_y_mm = float(mesh.z_um[-1]) * 1.0e-3
    gap_um = float(layer["start_gap_um"])
    n_layers = int(layer["vertical_layers"])

    up0 = float(layer["upward_velocity_m_s"])
    vr0 = float(layer["radial_velocity_m_s"])
    decay_r = max(r_max_um * float(layer["velocity_decay_radius_fraction"]), 1.0e-9)
    boost = float(layer["velocity_layer_boost"])

    nodes: list[str] = []
    elems: list[str] = []
    velocities: list[str] = []
    rows: list[dict[str, str]] = []
    nid = start_node
    eid = start_elem
    marker_count = 0
    velocity_node_count = 0

    radial_centers = [0.0]
    r = dr
    while r <= r_max_um + 1.0e-9:
        radial_centers.append(r)
        r += dr

    for layer_id in range(n_layers):
        z_um = gap_um + (layer_id + 0.5) * dz
        for r_um in radial_centers:
            profile = math.exp(-2.0 * (r_um / decay_r) ** 2)
            vy = up0 * profile * (1.0 + boost * layer_id)
            vx = vr0 * (r_um / max(r_max_um, 1e-9)) * profile
            if r_um == 0.0:
                vx = 0.0
            cx = r_um * 1.0e-3
            cy = top_y_mm + z_um * 1.0e-3
            n1, n2, n3, n4 = nid, nid + 1, nid + 2, nid + 3
            coords = [
                (cx - half, cy - half, 0.0),
                (cx + half, cy - half, 0.0),
                (cx + half, cy + half, 0.0),
                (cx - half, cy + half, 0.0),
            ]
            # Keep r >= 0 for axisymmetric display; collapse tiny negative corner at axis.
            if r_um == 0.0:
                coords[0] = (0.0, coords[0][1], coords[0][2])
                coords[3] = (0.0, coords[3][1], coords[3][2])
            for local, (x, y, z) in enumerate(coords):
                this_nid = nid + local
                nodes.append(f"{this_nid:8d}{x:16.7e}{y:16.7e}{z:16.7e}")
                velocities.append(
                    i10(this_nid) + f10(vx) + f10(vy) + f10(0.0)
                    + f10(0.0) + f10(0.0) + f10(0.0)
                )
                velocity_node_count += 1
            elems.append(f"{eid:8d}{2:8d}{n1:8d}{n2:8d}{n3:8d}{n4:8d}")
            rows.append({
                "case": case.name,
                "marker_id": marker_count + 1,
                "element_id": eid,
                "center_r_um": f"{r_um:.6f}",
                "center_height_above_surface_um": f"{z_um:.6f}",
                "vx_m_s": f"{vx:.6f}",
                "vy_m_s": f"{vy:.6f}",
                "layer_id": str(layer_id),
            })
            marker_count += 1
            nid += 4
            eid += 1

    meta = {
        "ejecta_markers": marker_count,
        "ejecta_nodes": velocity_node_count,
    }
    return nodes, elems, velocities, rows, meta


def insert_before_end(text: str, block: str) -> str:
    marker = "*END"
    idx = text.rfind(marker)
    if idx < 0:
        return text + "\n" + block
    return text[:idx] + block + text[idx:]


def rewrite_base_text(text: str, old_case: str, new_case: str) -> str:
    text = text.replace(f"v41_{old_case}.k", f"v50_{new_case}.k")
    text = text.replace("Generated by scripts/build_v41_dynamic_ablation_deletion.py", "Generated by scripts/build_v50_dynamic_ejecta_particle_pilot.py")
    text = text.replace("V4B dynamic ablation with pre-deleted vapor-zone elements.", "V5A dynamic ablation with explicit ejecta marker layer.")
    text = text.replace(f"V41 V4B predeleted ablation {old_case}", f"V50 V5A ejecta marker plume {new_case}")
    text = text.replace(f"Silicon V4B predeleted ablation {old_case}", f"Silicon substrate V5A {new_case}")
    text = text.replace("V4B pre-deletes vapor-zone elements by omitting them from *ELEMENT_SHELL.", "V5A keeps the V4C crater and adds explicit ejecta marker shell patches above it.")
    return text


def build_v50_text(case: V41Case, mesh, cfg: dict, v17_cfg: dict) -> tuple[str, dict, list[dict[str, str]]]:
    case_cfg = deepcopy(cfg)
    case_cfg["deletion_model"]["recoil_velocity_m_s"] = float(case_cfg["selected_case_runtime"]["recoil_velocity_m_s"])
    text, meta, _removed = build_k_text(case, mesh, case_cfg, v17_cfg)
    text = rewrite_base_text(text, case.name, case.name)

    start_node = (mesh.NR + 1) * (mesh.NZ + 1) + 1
    start_elem = mesh.NR * mesh.NZ + 1
    nodes, elems, velocities, marker_rows, plume_meta = ejecta_marker_geometry(
        mesh, case, cfg, v17_cfg, start_node=start_node, start_elem=start_elem
    )

    emat = cfg["ejecta_material"]
    mat2_line = (
        i10(2) + f10(float(emat["rho_kg_mm3"]))
        + f10(float(emat["youngs_modulus_GPa"]))
        + f10(float(emat["poisson_ratio"]))
    )
    block = f"""$ ---------------------------------------------------------------------------
$ V5A explicit ejecta marker shell patches.  These are Lagrangian marker
$ elements for plume visualization, not a calibrated SPH/ALE gas model yet.
$ ---------------------------------------------------------------------------
*MAT_ELASTIC
$#     mid        ro         e        pr
{mat2_line}
$
*SECTION_SHELL
{i10(2)}{i10(15)}
{f10(1.0)}{f10(1.0)}{f10(1.0)}{f10(1.0)}
$
*PART
Ejecta marker plume V5A {case.name}
{i10(2)}{i10(2)}{i10(2)}
$
*NODE
""" + "\n".join(nodes) + "\n$\n"
    block += "*ELEMENT_SHELL\n" + "\n".join(elems) + "\n$\n"
    block += (
        "*INITIAL_VELOCITY_NODE\n"
        "$#     nid        vx        vy        vz       vrx       vry       vrz\n"
        + "\n".join(velocities)
        + "\n$\n"
    )
    text = insert_before_end(text, block)
    text = text.replace("$ ============================================================================", f"$  Ejecta marker elements: {plume_meta['ejecta_markers']}\n$  Ejecta marker nodes: {plume_meta['ejecta_nodes']}\n$ ============================================================================", 1)
    meta.update(plume_meta)
    return text, meta, marker_rows


def main() -> int:
    project_root = Path(__file__).resolve().parents[1]
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--toml", type=Path, default=project_root / "config" / "v50_dynamic_ejecta_particle_pilot.toml")
    ap.add_argument("--out-dir", type=Path, default=project_root / "models" / "v50_dynamic_ejecta_particle_pilot")
    args = ap.parse_args()

    cfg = load_toml(args.toml)
    v17_cfg = load_toml(project_root / cfg["source"]["v17_config"])
    mesh = build_mesh(v17_cfg)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    registry_rows: list[dict[str, str]] = []
    marker_rows_all: list[dict[str, str]] = []
    for sc in cfg["selected_cases"]:
        case = V41Case(name=str(sc["name"]), Ep_uJ=float(sc["Ep_uJ"]), notes=str(sc.get("notes", "")))
        cfg["selected_case_runtime"] = {"recoil_velocity_m_s": float(sc["recoil_velocity_m_s"])}
        text, meta, marker_rows = build_v50_text(case, mesh, cfg, v17_cfg)
        k_name = f"v50_{case.name}.k"
        k_path = args.out_dir / k_name
        nbytes = write_k(text, k_path)
        marker_rows_all.extend(marker_rows)
        registry_rows.append({
            "name": case.name,
            "Ep_uJ": f"{case.Ep_uJ:g}",
            "k_file": f"models/v50_dynamic_ejecta_particle_pilot/{k_name}",
            "removed_elements": str(meta["removed_elements"]),
            "recoil_nodes": str(meta["recoil_nodes"]),
            "ejecta_markers": str(meta["ejecta_markers"]),
            "ejecta_nodes": str(meta["ejecta_nodes"]),
            "recoil_velocity_m_s": f"{float(sc['recoil_velocity_m_s']):.6f}",
            "run_lsdyna_final": "true",
            "notes": case.notes,
        })
        print(f"[OK] {k_path.name} ({nbytes:,} bytes): ejecta_markers={meta['ejecta_markers']}")

    reg_path = args.out_dir / "v50_case_registry.csv"
    with reg_path.open("w", newline="", encoding="utf-8") as fh:
        wr = csv.DictWriter(fh, fieldnames=list(registry_rows[0].keys()))
        wr.writeheader()
        wr.writerows(registry_rows)
    marker_path = args.out_dir / "v50_ejecta_markers.csv"
    with marker_path.open("w", newline="", encoding="utf-8") as fh:
        wr = csv.DictWriter(fh, fieldnames=list(marker_rows_all[0].keys()))
        wr.writeheader()
        wr.writerows(marker_rows_all)
    print(f"[OK] registry -> {reg_path}")
    print(f"[OK] ejecta markers -> {marker_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
