"""
build_v42_dynamic_recoil_sweep.py
=================================

Generate V4C recoil-drive sweep decks.

V4C reuses the V4B pre-deleted-crater builder, but varies the recoil velocity
case by case to test dynamic response sensitivity.

Run from project root:
    python scripts\\build_v42_dynamic_recoil_sweep.py
"""

from __future__ import annotations

import argparse
import csv
import sys
import tomllib
from copy import deepcopy
from pathlib import Path

_THIS_DIR = Path(__file__).resolve().parent
if str(_THIS_DIR) not in sys.path:
    sys.path.insert(0, str(_THIS_DIR))

from _build_v17_case import build_mesh, write_k  # noqa: E402
from build_v41_dynamic_ablation_deletion import (  # noqa: E402
    V41Case,
    build_k_text,
    load_toml,
)


if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass


def rewrite_deck_label(text: str, old_case: str, new_case: str) -> str:
    text = text.replace(f"v41_{old_case}.k", f"v42_{new_case}.k")
    text = text.replace("Generated by scripts/build_v41_dynamic_ablation_deletion.py", "Generated by scripts/build_v42_dynamic_recoil_sweep.py")
    text = text.replace("V4B dynamic ablation with pre-deleted vapor-zone elements.", "V4C recoil-drive sweep on pre-deleted vapor-zone elements.")
    text = text.replace(f"V41 V4B predeleted ablation {old_case}", f"V42 V4C recoil sweep {new_case}")
    text = text.replace(f"Silicon V4B predeleted ablation {old_case}", f"Silicon V4C recoil sweep {new_case}")
    text = text.replace("V4B pre-deletes vapor-zone elements by omitting them from *ELEMENT_SHELL.", "V4C varies recoil velocity on a V4B pre-deleted crater.")
    return text


def main() -> int:
    project_root = Path(__file__).resolve().parents[1]
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--toml",
        type=Path,
        default=project_root / "config" / "v42_dynamic_recoil_sweep.toml",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=project_root / "models" / "v42_dynamic_recoil_sweep",
    )
    args = ap.parse_args()

    cfg = load_toml(args.toml)
    v17_cfg = load_toml(project_root / cfg["source"]["v17_config"])
    mesh = build_mesh(v17_cfg)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 78)
    print("V4C -- build recoil-drive sweep decks")
    print(f"  source mesh: NR x NZ = {mesh.NR} x {mesh.NZ}")
    print(f"  nodes = {mesh.stats['n_nodes']}, elements = {mesh.stats['n_elements']}")
    print("=" * 78)

    registry_rows = []
    removed_rows = []
    for sc in cfg["selected_cases"]:
        case_name = str(sc["name"])
        recoil = float(sc["recoil_velocity_m_s"])
        case_cfg = deepcopy(cfg)
        case_cfg["deletion_model"]["recoil_velocity_m_s"] = recoil

        case = V41Case(
            name=case_name,
            Ep_uJ=float(sc["Ep_uJ"]),
            notes=str(sc.get("notes", "")),
        )
        text, meta, removed = build_k_text(case, mesh, case_cfg, v17_cfg)
        text = rewrite_deck_label(text, old_case=case_name, new_case=case_name)
        k_name = f"v42_{case_name}.k"
        k_path = args.out_dir / k_name
        nbytes = write_k(text, k_path)

        for eid in removed:
            j = (eid - 1) // mesh.NR
            i = (eid - 1) % mesh.NR
            removed_rows.append({
                "case": case_name,
                "element_id": eid,
                "i": i,
                "j": j,
                "r_center_um": f"{0.5 * (mesh.r_um[i] + mesh.r_um[i + 1]):.6f}",
                "z_center_um": f"{0.5 * (mesh.z_um[j] + mesh.z_um[j + 1]):.6f}",
                "reason": "pre-deleted vapor-zone element",
            })

        registry_rows.append({
            "name": case_name,
            "Ep_uJ": f"{case.Ep_uJ:g}",
            "k_file": f"models/v42_dynamic_recoil_sweep/{k_name}",
            "vapor_radius_um": f"{meta['vapor_radius_um']:.6f}",
            "removed_elements": meta["removed_elements"],
            "kept_elements": meta["kept_elements"],
            "recoil_nodes": meta["recoil_nodes"],
            "recoil_velocity_m_s": f"{recoil:.6f}",
            "axis_top_node_id": meta["axis_top_node_id"],
            "run_lsdyna_final": "true",
            "notes": case.notes,
        })
        print(
            f"[OK] {k_path.name} ({nbytes:,} bytes): "
            f"recoil={recoil:g} m/s, removed={meta['removed_elements']}, "
            f"recoil_nodes={meta['recoil_nodes']}"
        )

    reg_path = args.out_dir / "v42_case_registry.csv"
    with reg_path.open("w", newline="", encoding="utf-8") as fh:
        wr = csv.DictWriter(fh, fieldnames=list(registry_rows[0].keys()))
        wr.writeheader()
        wr.writerows(registry_rows)
    print(f"[OK] registry -> {reg_path}")

    rem_path = args.out_dir / "v42_removed_elements.csv"
    fieldnames = [
        "case", "element_id", "i", "j", "r_center_um", "z_center_um", "reason",
    ]
    with rem_path.open("w", newline="", encoding="utf-8") as fh:
        wr = csv.DictWriter(fh, fieldnames=fieldnames)
        wr.writeheader()
        wr.writerows(removed_rows)
    print(f"[OK] removed elements -> {rem_path}")
    print("[DONE] V4C recoil sweep decks generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
