"""
build_v61_lammps_ttm_mod_ablation_scan.py
=========================================

Generate V6B LAMMPS ttm/mod laser ablation scout inputs.

Run from project root:
    python scripts\\build_v61_lammps_ttm_mod_ablation_scan.py
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    import tomli as tomllib  # type: ignore


if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass


def load_toml(path: Path) -> dict:
    with path.open("rb") as f:
        return tomllib.load(f)


def steps(duration_ps: float, timestep_ps: float) -> int:
    return max(1, int(round(duration_ps / timestep_ps)))


def fluence_to_peak_intensity(fluence_j_cm2: float, pulse_width_ps: float, scale: float) -> float:
    """Return a scout peak intensity in eV/(ps A^2).

    1 J/cm^2 = 624.1509 eV/A^2.  The exact ttm/mod temporal normalization
    should be calibrated; this first scout uses F/tau as a transparent starting
    point and stores the chosen value in the registry.
    """
    fluence_eV_A2 = fluence_j_cm2 * 624.1509074460763
    return scale * fluence_eV_A2 / pulse_width_ps


def ttm_mod_file_text(cfg: dict, case: dict) -> str:
    p = cfg["ttm_mod_parameters"]
    laser = cfg["laser"]
    grid = cfg["ttm_grid"]
    I0 = fluence_to_peak_intensity(
        float(case["fluence_J_cm2"]),
        float(laser["pulse_width_ps"]),
        float(laser["intensity_scale"]),
    )
    values = [
        ("a_0, energy/(temperature*electron) units", p["a_0"]),
        ("a_1, energy/(temperature^2*electron) units", p["a_1"]),
        ("a_2, energy/(temperature^3*electron) units", p["a_2"]),
        ("a_3, energy/(temperature^4*electron) units", p["a_3"]),
        ("a_4, energy/(temperature^5*electron) units", p["a_4"]),
        ("C_0, energy/(temperature*electron) units", p["C_0"]),
        ("A, 1/temperature units", p["A"]),
        ("rho_e, electrons/volume units", p["rho_e"]),
        ("D_e, length^2/time units", p["D_e"]),
        ("gamma_p, mass/time units", p["gamma_p"]),
        ("gamma_s, mass/time units", p["gamma_s"]),
        ("v_0, length/time units", p["v_0"]),
        ("I_0, energy/(time*length^2) units", I0),
        ("lsurface, electron grid units (positive integer)", 0),
        ("rsurface, electron grid units (positive integer)", 1),
        ("l_skin, length units", float(laser["absorption_depth_nm"]) * 10.0),
        ("tau, time units", float(laser["pulse_width_ps"])),
        ("B, dimensionless", p["B"]),
        ("lambda, length units", p["lambda"]),
        ("n_ion, ions/volume units", p["n_ion"]),
        ("surface_movement: 0 to disable tracking of surface motion, 1 to enable", p["surface_movement"]),
        ("T_e_min, temperature units", p["T_e_min"]),
    ]
    lines: list[str] = []
    for label, value in values:
        lines.append(str(label))
        lines.append(f"{float(value):.12g}" if isinstance(value, float) else str(value))
    return "\n".join(lines) + "\n"


def input_text(cfg: dict, case: dict) -> str:
    geom = cfg["geometry"]
    groups = cfg["groups"]
    mat = cfg["material"]
    run = cfg["run_control"]
    grid = cfg["ttm_grid"]

    nx = int(geom["nx_cells"])
    ny = int(geom["ny_cells"])
    nz = int(geom["nz_cells"])
    nz_box = nz + int(geom["vacuum_cells_z"])
    alat = float(geom["lattice_constant_A"])
    dt = float(run["timestep_ps"])
    eq_steps = steps(float(run["equilibration_ps"]), dt)
    prod_steps = steps(float(case["production_ps"]), dt)
    dump_steps = steps(float(run["dump_interval_ps"]), dt)
    thermo_steps = int(run["thermo_interval_steps"])
    mobile_lo = float(groups["bottom_fixed_thickness_A"])
    bath_hi = mobile_lo + float(groups["bottom_thermostat_thickness_A"])
    name = str(case["name"])

    return f"""# V6B LAMMPS ttm/mod Si laser ablation scout
# case: {name}
# Generated by scripts/build_v61_lammps_ttm_mod_ablation_scan.py

units           metal
dimension       3
boundary        p p p
atom_style      atomic

variable        alat equal {alat:.6f}
lattice         diamond ${{alat}}
region          box block 0 {nx} 0 {ny} 0 {nz_box} units lattice
create_box      1 box
region          si block 0 {nx} 0 {ny} 0 {nz} units lattice
create_atoms    1 region si

mass            1 {float(mat['mass_amu']):.6f}
pair_style      {mat['pair_style']}
pair_coeff      * * {mat['pair_coeff_file']} Si

neighbor        2.0 bin
neigh_modify    every 5 delay 0 check yes

region          bottom block INF INF INF INF INF {mobile_lo:.6f} units box
region          bath block INF INF INF INF {mobile_lo:.6f} {bath_hi:.6f} units box
group           bottom region bottom
group           bath region bath
group           mobile subtract all bottom

compute         peatom all pe/atom
compute         keatom all ke/atom
compute         satom all stress/atom NULL

timestep        {dt:.8f}
velocity        mobile create 300.0 4928459 mom yes rot yes dist gaussian
velocity        bottom set 0.0 0.0 0.0
fix             hold bottom setforce 0.0 0.0 0.0

min_style       cg
minimize        1.0e-8 1.0e-10 500 5000

fix             nve mobile nve
fix             bathfix bath langevin 300.0 300.0 0.1 827364 zero yes
thermo          {thermo_steps}
thermo_style    custom step time temp pe ke etotal press
run             {eq_steps}
unfix           bathfix

# Real laser-source scout using LAMMPS fix ttm/mod.
fix             twotemp all ttm/mod {int(grid['seed'])} v61_{name}.ttm_mod {int(grid['nx'])} {int(grid['ny'])} {int(grid['nz'])} set {float(grid['initial_electron_temperature_K']):.3f} outfile {dump_steps} Te_out

dump            atomdump all custom {dump_steps} dump.v61_{name}.lammpstrj id type x y z vx vy vz c_keatom c_peatom c_satom[1] c_satom[2] c_satom[3] c_satom[4] c_satom[5] c_satom[6]
dump_modify     atomdump sort id
run             {prod_steps}

write_data      final.v61_{name}.data

unfix           twotemp
unfix           nve
unfix           hold
"""


def main() -> int:
    project_root = Path(__file__).resolve().parents[1]
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--toml", type=Path, default=project_root / "config" / "v61_lammps_ttm_mod_ablation_scan.toml")
    ap.add_argument("--out-dir", type=Path, default=project_root / "models" / "v61_lammps_ttm_mod_ablation_scan")
    args = ap.parse_args()

    cfg = load_toml(args.toml)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    registry = []
    atoms = int(cfg["geometry"]["nx_cells"]) * int(cfg["geometry"]["ny_cells"]) * int(cfg["geometry"]["nz_cells"]) * 8

    for case in cfg["selected_cases"]:
        name = str(case["name"])
        in_path = args.out_dir / f"v61_{name}.in"
        ttm_path = args.out_dir / f"v61_{name}.ttm_mod"
        in_path.write_text(input_text(cfg, case), encoding="utf-8")
        ttm_path.write_text(ttm_mod_file_text(cfg, case), encoding="utf-8")
        registry.append({
            "name": name,
            "fluence_J_cm2": f"{float(case['fluence_J_cm2']):.6g}",
            "I0_eV_ps_A2": f"{fluence_to_peak_intensity(float(case['fluence_J_cm2']), float(cfg['laser']['pulse_width_ps']), float(cfg['laser']['intensity_scale'])):.8g}",
            "pulse_width_ps": f"{float(cfg['laser']['pulse_width_ps']):.6g}",
            "production_ps": f"{float(case['production_ps']):.6g}",
            "input_file": str(in_path.relative_to(project_root)).replace("\\", "/"),
            "ttm_mod_file": str(ttm_path.relative_to(project_root)).replace("\\", "/"),
            "run_lammps_hint": str(case.get("run_lammps_hint", True)).lower(),
            "atoms_expected": str(atoms),
            "notes": str(case.get("notes", "")),
        })

    reg_path = args.out_dir / "v61_case_registry.csv"
    with reg_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(registry[0].keys()))
        writer.writeheader()
        writer.writerows(registry)

    print(f"[OK] {reg_path}")
    for row in registry:
        print(f"[OK] {row['input_file']} atoms={row['atoms_expected']} F={row['fluence_J_cm2']} J/cm2")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
