"""
make_v44_lsprepost_cfiles.py
============================

Generate LS-PrePost command files for extracting real d3plot fields.

Run from project root:
    python scripts\\make_v44_lsprepost_cfiles.py

Then execute the generated .cfile files with LS-PrePost, or use:
    powershell -ExecutionPolicy Bypass -File scripts\\run_v44_lsprepost_export.ps1
"""

from __future__ import annotations

import argparse
import csv
import sys
import tomllib
from pathlib import Path


if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass


DISPLACEMENT_OUTPUT_FLAGS = "1 0 1 0 0 1 0 0 0 0 0 0 0 0 1.000000"
SHELL_SCALAR_OUTPUT_FLAGS = "1 0 1 0 0 0 0 1 0 0 0 0 0 0 1.000000"


def load_toml(path: Path) -> dict:
    with path.open("rb") as fh:
        return tomllib.load(fh)


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def q(path: Path) -> str:
    return str(path).replace("\\", "/")


def selected_case_names(cfg: dict) -> list[str]:
    return [str(row["name"]) for row in cfg.get("selected_cases", [])]


def enabled_exports(cfg: dict) -> list[dict]:
    return [row for row in cfg.get("field_exports", []) if bool(row.get("enabled", False))]


def write_case_cfile(root: Path, output_root: Path, cfg: dict, case: str) -> Path:
    src = cfg["source"]
    out = cfg["output"]
    states = [int(v) for v in cfg["states"]["state_numbers"]]
    exports = enabled_exports(cfg)

    result_dir = output_root / src["result_root"] / case
    d3plot = result_dir / "d3plot"
    command_dir = output_root / out["command_root"] / case
    field_dir = output_root / out["field_root"] / case
    command_dir.mkdir(parents=True, exist_ok=True)
    field_dir.mkdir(parents=True, exist_ok=True)

    cfile = command_dir / "export_fields.cfile"
    lines = [
        "$ Generated by scripts/make_v44_lsprepost_cfiles.py",
        "$ Open the real LS-DYNA binary plot and export selected state data.",
        f'open d3plot "{q(d3plot)}"',
    ]

    for state in states:
        state_dir = field_dir / f"state_{state:04d}"
        state_dir.mkdir(parents=True, exist_ok=True)
        for exp in exports:
            name = str(exp["name"])
            kind = str(exp["kind"])
            if kind == "nodal_displacement":
                target = state_dir / f"{name}.k"
                lines.append(f'output "{q(target)}" {state} {DISPLACEMENT_OUTPUT_FLAGS}')
            elif kind == "shell_element_scalar":
                fringe_command = str(exp.get("fringe_command", "")).strip()
                if fringe_command:
                    lines.append(fringe_command)
                target = state_dir / f"{name}.k"
                lines.append(f'output "{q(target)}" {state} {SHELL_SCALAR_OUTPUT_FLAGS}')
            else:
                raise ValueError(f"unsupported export kind: {kind}")

    lines.append("quit")
    cfile.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return cfile


def main() -> int:
    default_root = Path(__file__).resolve().parents[1]
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--project-root", type=Path, default=default_root)
    ap.add_argument("--output-root", type=Path, default=None)
    ap.add_argument("--config", type=Path, default=None)
    ap.add_argument("--case", default="all", help="case name or all")
    args = ap.parse_args()

    root = args.project_root.resolve()
    output_root = args.output_root.resolve() if args.output_root else root
    config_path = args.config or root / "config" / "v44_lsprepost_real_field_extract.toml"
    cfg = load_toml(config_path)

    registry = root / cfg["source"]["case_registry"]
    registry_rows = {row["name"]: row for row in read_csv_rows(registry)}
    requested = selected_case_names(cfg) if args.case == "all" else [args.case]

    written = []
    for case in requested:
        if case not in registry_rows:
            raise SystemExit(f"case not found in registry: {case}")
        cfile = write_case_cfile(root, output_root, cfg, case)
        written.append(cfile)

    for path in written:
        print(f"[OK] {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

